// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAycMCShCpRUNR_D5I9G5TQMA9ab25U8',
    appId: '1:943151114409:android:b30e768df65ea9c03321b8',
    messagingSenderId: '943151114409',
    projectId: 'emergency-wallet-485ce',
    databaseURL: 'https://emergency-wallet-485ce-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-wallet-485ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnIl0XErmhCA9uuIDF8r_y9otQUokVmk',
    appId: '1:943151114409:ios:d757d6ebafea82cc3321b8',
    messagingSenderId: '943151114409',
    projectId: 'emergency-wallet-485ce',
    databaseURL: 'https://emergency-wallet-485ce-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-wallet-485ce.firebasestorage.app',
    iosClientId: '943151114409-4ngt361fkh1flpnu22t36ns15g4khk04.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyWallet',
  );
}
